### ISSUE TITLE
no implicit conversion of Array into String (TypeError)  if File.exist?(path)

### ISSUE THREAD

**Issue by AghaShayan123** [aws/aws-codedeploy-agent#357] opened 2023-03-26 10:54 UTC
I am installing aws-codedeploy-agent but getting error of ruby 

![Screenshot 2023-03-25 182257](https://user-images.githubusercontent.com/39364365/227770996-b410f953-f563-4005-b51b-00ff260733aa.png)

**Comment by mwjones-aws** [comment] 2023-03-27 19:52
Closing as duplicate of https://github.com/aws/aws-codedeploy-agent/issues/355

**Closed by mwjones-aws** 2023-03-27 19:52 UTC
