### ISSUE TITLE
Installation fails for ruby 2.7.x

### ISSUE THREAD

**Issue by cmllamosas** [aws/aws-codedeploy-agent#242] opened 2020-04-23 22:54 UTC
Installation fails for ruby 2.7.x, is default version on [Ubuntu 20.04 LTS (Focal Fossa)](https://cloud-images.ubuntu.com/locator/ec2/)

- AMI-ID: ami-068663a3c619dd892
- AMI-ID: ami-00579fbb15b954340

Of course since only up to 2.5 is supported as seen in [here](https://github.com/aws/aws-codedeploy-agent/blob/master/bin/install#L88):

````
  def supported_ruby_versions
    ['2.5', '2.4', '2.3', '2.2', '2.1', '2.0']
  end
````

**Comment by brblck** [comment] 2020-05-26 20:26
Closing as duplicate of https://github.com/aws/aws-codedeploy-agent/issues/239.

**Closed by brblck** 2020-05-26 20:26 UTC
Labels: duplicate
