### ISSUE TITLE
deployment failed during install phase with error : No such file or directory @ rb_sysopen 

### ISSUE THREAD

**Issue by rubashanti** [aws/aws-codedeploy-agent#251] opened 2020-06-29 13:03 UTC
the deployment failed with error : No such file or directory @ rb_sysopen  -- file name.

however, from code deploy agent log I can see that the file has been copied, and the file name + path length is only 141 , so it's not exceeding the max length.

There is nothing in Appspec command that would remove the directory or any files, it just stop the IIS
Can you please advise.

**Comment by cechavarria** [comment] 2020-06-29 18:06
Hi,

We are getting the same error:

"No such file or directory @ rb_sysopen -"

The path that follows is 195 characters long (100 being used by the path used by CodeDeploy itself).

It's not clear whether this is a character limit (there's no where in the official documentation a reference to that limit, you can read on forums about a 255 limit but those post are years old) or whether the issue is the how the agent works and something related to ruby-zip.

**Comment by rubashanti** [comment] 2020-07-05 08:47
the limit is not related to code deploy, it's related to windows
If the Filename + Path is greater than 260 character, the cx will get this issue, This is Windows limitation as describe here -- https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#maxim...

**Comment by hegyre** [comment] 2020-08-25 09:37
Could it be because the file handle is still locked by Windows ?
How could we tell CodeDeploy to force-close the handle for that file?

**Comment by brblck** [comment] 2020-08-28 23:07
Can you share agent logs from this incident?

**Comment by hegyre** [comment] 2020-09-08 10:01
Hello @brblck,
Using CodeDeploy 1.1.2, here's the logs (only failed part):

```
2020-08-25T08:51:04 DEBUG [codedeploy-agent(13348)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Calling PutHostCommandComplete: "Code Error" 
2020-08-25T08:51:04 INFO  [codedeploy-agent(13348)]: Version file found in C:/ProgramData/Amazon/CodeDeploy/.version with agent version OFFICIAL_1.1.2.1855_msi.
2020-08-25T08:51:04 INFO  [codedeploy-agent(13348)]: [Aws::CodeDeployCommand::Client 200 0.121926 0 retries] put_host_command_complete(command_status:"Failed",diagnostics:{format:"JSON",payload:"{\"error_code\":5,\"script_name\":\"\",\"message\":\"Permission denied @ rb_sysopen - d:/acs_services/ACS_UK/bin/ACS.Common.Data.dll\",\"log\":\"\"}"},host_command_identifier:"eyJiYXRjaElkIjoiY2M4OTE0MWJjYjhkZGJhNmZlZmMzMTU5YmY5ZDgxNjkvcHVibGljMDA2IiwiZGVwbG95bWVudElkIjoiQ29kZURlcGxveS9ldS13ZXN0LTEvcHJvZC9vcnBoZXVzOnB1YmxpYzAwMy8yMDAyNzQ4MDA2NjY6ZC01UjNYSkI0VjUiLCJob3N0SWQiOiJhcm46YXdzOmVjMjpldS13ZXN0LTE6MjAwMjc0ODAwNjY2Omluc3RhbmNlL2ktMGZhMjRkZjRhMGExYjQ2MTgiLCJjb21tYW5kSWQiOiJBcG9sbG9EZXBsb3lDb250cm9sU2VydmljZXxhcm46YXdzOmVjMjpldS13ZXN0LTE6MjAwMjc0ODAwNjY2Omluc3RhbmNlL2ktMGZhMjRkZjRhMGExYjQ2MTh8N3wwIiwiY29tbWFuZE5hbWUiOiJJbnN0YWxsIiwiY29tbWFuZEluZGV4Ijo3LCJhdHRlbXB0SW5kZXgiOjF9")  

2020-08-25T08:51:04 ERROR [codedeploy-agent(13348)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: Errno::EACCES - Permission denied @ rb_sysopen - d:/acs_services/ACS_UK/bin/ACS.Common.Data.dll - C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:1393:in `initialize'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:1393:in `open'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:1393:in `block in copy_file'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/install_instruction.rb:237:in `execute'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:49:in `block (2 levels) in install'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:48:in `each'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:48:in `block in install'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:47:in `open'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:47:in `install'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:136:in `block in <class:CommandExecutor>'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:68:in `execute_command'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:115:in `process_command'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:97:in `acknowledge_and_process_command'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocrDA3.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:76:in `block in perform'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocrDA3.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocrDA3.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocrDA3.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocrDA3.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocrDA3.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocrDA3.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocrDA3.tmp/lib/ruby/gems/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2020-08-25T08:51:04 WARN  [codedeploy-agent(13348)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Calling PutHostCommandComplete: "Code Error"
```

I've managed to do a workaround by writing a script to kill the process attached to locked files (if any) in the destination folder, in the BeforeInstall hook.

**Comment by hegyre** [comment] 2020-09-22 08:07
Hello @brblck ,

The issue appeared again, and no files were locked this time...

The logs are the same as in my previous comment...

Please kindly help.

Do you think it's resolved in CodeDeploy v1.2.1 ? as I don't see any changelog between 1.1.2 and 1.2.1...

**Comment by hegyre** [comment] 2020-09-22 08:11
Sorry it's not exactly the same log as above. Previous it was a Errno::EACCES - Permission denied @ rb_sysopen
Now it's a Errno::ENOENT - No such file or directory @ rb_sysopen, but still on the same file:

```2020-09-22T05:37:46 DEBUG [codedeploy-agent(12812)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Calling PutHostCommandComplete: "Code Error" 
2020-09-22T05:37:46 INFO  [codedeploy-agent(12812)]: Version file found in C:/ProgramData/Amazon/CodeDeploy/.version with agent version OFFICIAL_1.1.2.1855_msi.
2020-09-22T05:37:46 INFO  [codedeploy-agent(12812)]: [Aws::CodeDeployCommand::Client 200 0.079303 0 retries] put_host_command_complete(command_status:"Failed",diagnostics:{format:"JSON",payload:"{\"error_code\":5,\"script_name\":\"\",\"message\":\"No such file or directory @ rb_sysopen - d:/acs_services/ACS_DE/bin/ACS.Common.Data.dll\",\"log\":\"\"}"},host_command_identifier:"eyJiYXRjaElkIjoiMWE1ZTMxMTMxZmJkZjQ0Y2FkMzEwMDUyNTdlNmQ2NzgvcHVibGljMDAzIiwiZGVwbG95bWVudElkIjoiQ29kZURlcGxveS9ldS13ZXN0LTEvcHJvZC9vcnBoZXVzOnB1YmxpYzAwNS8yMDAyNzQ4MDA2NjY6ZC1HMFczT0NHRDYiLCJob3N0SWQiOiJhcm46YXdzOmVjMjpldS13ZXN0LTE6MjAwMjc0ODAwNjY2Omluc3RhbmNlL2ktMDg0MWE1YzcxZTExYTczMTMiLCJjb21tYW5kSWQiOiJBcG9sbG9EZXBsb3lDb250cm9sU2VydmljZXxhcm46YXdzOmVjMjpldS13ZXN0LTE6MjAwMjc0ODAwNjY2Omluc3RhbmNlL2ktMDg0MWE1YzcxZTExYTczMTN8N3wwIiwiY29tbWFuZE5hbWUiOiJJbnN0YWxsIiwiY29tbWFuZEluZGV4Ijo3LCJhdHRlbXB0SW5kZXgiOjF9")  

2020-09-22T05:37:46 ERROR [codedeploy-agent(12812)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: Errno::ENOENT - No such file or directory @ rb_sysopen - d:/acs_services/ACS_DE/bin/ACS.Common.Data.dll - C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:1393:in `initialize'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:1393:in `open'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:1393:in `block in copy_file'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/install_instruction.rb:237:in `execute'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:49:in `block (2 levels) in install'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:48:in `each'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:48:in `block in install'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:47:in `open'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:47:in `install'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:136:in `block in <class:CommandExecutor>'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:68:in `execute_command'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:115:in `process_command'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:97:in `acknowledge_and_process_command'
C:/Users/S-ALSD~1/AppData/Local/Temp/ocr210B.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:76:in `block in perform'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocr210B.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocr210B.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocr210B.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocr210B.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocr210B.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocr210B.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
C:/Users/s-ALSDeploy-prd/AppData/Local/Temp/ocr210B.tmp/lib/ruby/gems/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2020-09-22T05:37:46 WARN  [codedeploy-agent(12812)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Calling PutHostCommandComplete: "Code Error" ```

**Comment by brblck** [comment] 2020-09-22 18:58
@hegyre looking at the logs this is pretty clearly a file system permission issue. 

Do you know what user the CodeDeploy agent was installed and is running under? 
Have you been able to confirm that user has access to this file system location?

**Comment by hegyre** [comment] 2020-09-23 08:01
Hello @brblck ,
I've opened AWS Support case ID 7409028831, maybe you can help them. Some pre-analysis have been done already.

To me it's difficult to understand why it could be a permission issue.

All the files were previously deployed by CodeDeploy, with the same user s-ALSDeploy-prd@<domain>
A re-deploy, after some minutes, worked successfully. Thus I cannot explain the issue.

Also, if this would be a permission issue, error would be Errno::EACCES - Permission denied @ rb_sysopen
However, my last log shown a Errno::ENOENT - No such file or directory @ rb_sysopen

And for your last question, yes the user has access to the destnation folder and files, I've checked that already...

Also Notice the log format that is not always the same pattern:
C:/Users/S-ALSD~1/AppData/...
C:/Users/s-ALSDeploy-prd/AppData/...

**Comment by philstrong** [comment] 2021-01-13 20:53
resolved by premium support

**Closed by philstrong** 2021-01-13 20:53 UTC

**Comment by mjkent** [comment] 2023-10-04 11:54
@philstrong How did you end up resolving this? We are seeing the same issue intermittently

**Comment by GFoley83** [comment] 2023-12-04 21:28
@philstrong could you please elaborate on what the solution is??
