### ISSUE TITLE
Aws::CodeDeployCommand::Errors::AccessDeniedException after /etc/init.d/codedeploy-agent restart

### ISSUE THREAD

**Issue by timgilbert** [aws/aws-codedeploy-agent#69] opened 2016-06-09 16:45 UTC
After I modified codedeploy-agent's config file to reduce the number of builds it keeps around, I restarted it to get it to reread the config file by running:

```
sudo /etc/init.d/codedeploy-agent restart
```

The restart itself worked fine, but after the agent came back up it started to report a bunch of "access denied" errors in its logs, and deployments to that instance ceased to work. Eventually I tried rebooting the server itself, at which point everything began to work properly again.

Here is the relevant section of my logs from `/var/log/aws/codedeploy-agent` from around the time I restarted the agent:

```
2016-06-06 21:02:20 INFO  [codedeploy-agent(6665)]: Version file found in /opt/codedeploy-agent/.version.
2016-06-06 21:03:20 INFO  [codedeploy-agent(6665)]: [Aws::CodeDeployCommand::Client 200 60.365945 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-east-1:XXXX:instance/i-YYYY")

2016-06-06 21:03:21 INFO  [codedeploy-agent(6665)]: Version file found in /opt/codedeploy-agent/.version.
2016-06-06 21:05:01 INFO  [codedeploy-agent(15321)]: Stopping master 6660
2016-06-06 21:05:01 INFO  [codedeploy-agent(6660)]: master 6660: Received TERM - stopping children and shutting down
2016-06-06 21:05:01 INFO  [codedeploy-agent(6665)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller of master 6660: Received TERM - setting internal shutting down flag and possibly finishing last run
2016-06-06 21:05:22 INFO  [codedeploy-agent(6665)]: [Aws::CodeDeployCommand::Client 200 121.037746 1 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-east-1:XXXX:instance/i-YYYY")

2016-06-06 21:05:23 INFO  [codedeploy-agent(6665)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller of master 6660: shutting down
2016-06-06 21:05:25 INFO  [codedeploy-agent(15352)]: master 15352: Spawned child 1/1
2016-06-06 21:05:25 INFO  [codedeploy-agent(15352)]: master 15352: Spawned child 1/1
2016-06-06 21:05:25 INFO  [codedeploy-agent(15356)]: On Premises config file does not exist or not readable
2016-06-06 21:05:25 INFO  [codedeploy-agent(15356)]: On Premises config file does not exist or not readable
2016-06-06 21:05:25 INFO  [codedeploy-agent(15356)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandExecutor: Archives to retain is: 1}
2016-06-06 21:05:25 INFO  [codedeploy-agent(15356)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandExecutor: Archives to retain is: 1}
2016-06-06 21:05:25 INFO  [codedeploy-agent(15356)]: Version file found in /opt/codedeploy-agent/.version.
2016-06-06 21:05:25 INFO  [codedeploy-agent(15356)]: Version file found in /opt/codedeploy-agent/.version.
2016-06-06 21:05:25 INFO  [codedeploy-agent(15356)]: [Aws::CodeDeployCommand::Client 400 0.062063 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-east-1:XXXX:instance/i-YYYY") Aws::CodeDeployCommand::Errors::AccessDeniedException

2016-06-06 21:05:25 INFO  [codedeploy-agent(15356)]: [Aws::CodeDeployCommand::Client 400 0.062063 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-east-1:XXXX:instance/i-YYYY") Aws::CodeDeployCommand::Errors::AccessDeniedException
```

I'm not sure why restarting the server would work, I tried it on a guess because I thought it might be IAM-related or something.

**Comment by amartyag** [comment] 2016-06-17 16:18
This might be related to failure to read the instance profile, which is used by the agent to authenticate. We will try to reproduce this issue. In the meantime, can you let us know:
1. Does this happen on every agent restart?
2. Does this happen on only that instance?
3. OS on that instance
Also, if you are able to reproduce this issue consistently, running the agent in debug mode [with verbose option](http://docs.aws.amazon.com/codedeploy/latest/userguide/agent-configuration-reference.html) can provide a lot of insight

Thanks

**Comment by viraptor** [comment] 2017-07-14 05:14
Spotted here as well, so I'll try to provide more info.
Instance came up with codedeploy-agent sending requests successfully. After service restart I get same result - `AccessDeniedException`. I also get the weird double-log issue.

It happens on every `/etc/init.d/codedeploy-agent restart`, but not on `service codedeploy-agent restart`.

OS is: `Ubuntu 14.04.5 LTS` with agent `OFFICIAL_1.0-1.1106_deb`.

With verbose logging, I can't see anything more related to the issue apart from the extra line:
```
2017-07-14 15:12:34 ERROR [codedeploy-agent(4886)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException -
```

**Comment by sanketmehta7** [comment] 2017-08-14 15:15
same thing happened for me as well i tried reducing number of revision value and after restart i was not able to deploy at all.

In log files i do get below response.

```
2017-08-14 14:53:29 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 14:53:29 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 14:54:59 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 14:54:59 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 14:54:59 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.040795 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 14:54:59 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.040795 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 14:54:59 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 14:54:59 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 14:56:29 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 14:56:29 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 14:56:29 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.021125 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 14:56:29 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.021125 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 14:56:29 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 14:56:29 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 14:57:59 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 14:57:59 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 14:57:59 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.058011 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 14:57:59 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.058011 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 14:57:59 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 14:57:59 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 14:59:29 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 14:59:29 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 14:59:29 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.056598 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 14:59:29 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.056598 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 14:59:29 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 14:59:29 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 15:00:59 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 15:00:59 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 15:00:59 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.021876 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 15:00:59 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.021876 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 15:00:59 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 15:00:59 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 15:02:29 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 15:02:29 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 15:02:29 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.018935 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 15:02:29 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.018935 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 15:02:29 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 15:02:29 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 15:03:59 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 15:03:59 INFO  [codedeploy-agent(13242)]: Version file found in /opt/codedeploy-agent/.version.
2017-08-14 15:03:59 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.018773 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 15:03:59 INFO  [codedeploy-agent(13242)]: [Aws::CodeDeployCommand::Client 400 0.018773 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:481994200611:instance/i-011e71a901c447bce") Aws::CodeDeployCommand::Errors::AccessDeniedException 

2017-08-14 15:03:59 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException - 
2017-08-14 15:03:59 ERROR [codedeploy-agent(13242)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Cannot reach InstanceService: Aws::CodeDeployCommand::Errors::AccessDeniedException -
```

before this to restart the agent on ec2 i run below commands

```
sudo /opt/codedeploy-agent/bin/codedeploy-agent restart
Stopping master 8506
Child processes still running. Master going down.
Pidfile /opt/codedeploy-agent/state/.pid/codedeploy-agent.pid present but no matching process running - cleaning up
[ec2-user@ip-172-31-24-108 conf]$ Started master 13238 with 1 children
```

**Comment by sanketmehta7** [comment] 2017-08-14 15:30
it however got fixed after i did `service codedeploy-agent restart.` as suggested by @viraptor  w/o needing to restart machine

**Comment by annamataws** [comment] 2018-08-02 18:01
Is this still affecting you with the new agent version?

**Comment by miradnan** [comment] 2018-09-29 05:18
I am facing same issue.

OS:
Ubuntu 16.04

```
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in `start'
/opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:43:in `block (2 levels) in <main>'
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:90:in `<main>'
2018-09-29 10:45:13 INFO  [codedeploy-agent(38799)]: master 38799: Received CHLD - cleaning dead child process
2018-09-29 10:45:13 INFO  [codedeploy-agent(38799)]: master 38799: been told to replace child 38803
2018-09-29 10:45:13 INFO  [codedeploy-agent(38799)]: master 38799: not enough child processes running - missing at least 1 - respawning
2018-09-29 10:45:18 INFO  [codedeploy-agent(38799)]: master 38799: Spawned child 1/1
2018-09-29 10:45:18 INFO  [codedeploy-agent(38865)]: On Premises config file does not exist or not readable
2018-09-29 10:45:22 ERROR [codedeploy-agent(38865)]: booting child: error during start or run: Errno::ECONNRESET - Connection reset by peer - <internal:prelude>:76:in `__read_nonblock'
<internal:prelude>:76:in `read_nonblock'
/usr/lib/ruby/2.3.0/net/protocol.rb:154:in `rbuf_fill'
/usr/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
/usr/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
/usr/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
/usr/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.10.104/lib/seahorse/client/net_http/patches.rb:29:in `block in new_transport_request'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.10.104/lib/seahorse/client/net_http/patches.rb:26:in `catch'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.10.104/lib/seahorse/client/net_http/patches.rb:26:in `new_transport_request'
/usr/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/usr/lib/ruby/2.3.0/net/http.rb:1156:in `get'
/opt/codedeploy-agent/lib/instance_metadata.rb:52:in `block in http_get'
/usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
/usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
/opt/codedeploy-agent/lib/instance_metadata.rb:51:in `http_get'
/opt/codedeploy-agent/lib/instance_metadata.rb:22:in `region'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:38:in `initialize'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `new'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `runner'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:32:in `block in prepare_run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2018-09-29 10:45:22 ERROR [codedeploy-agent(38865)]: booting child: error during start or run: SystemExit - exit - /opt/codedeploy-agent/lib/instance_agent/runner/child.rb:90:in `exit'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:90:in `rescue in with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2018-09-29 10:45:22 INFO  [codedeploy-agent(38799)]: master 38799: Received CHLD - cleaning dead child process
2018-09-29 10:45:22 INFO  [codedeploy-agent(38799)]: master 38799: been told to replace child 38865
2018-09-29 10:45:22 INFO  [codedeploy-agent(38799)]: master 38799: not enough child processes running - missing at least 1 - respawning
2018-09-29 10:45:27 INFO  [codedeploy-agent(38799)]: master 38799: Spawned child 1/1
2018-09-29 10:45:27 INFO  [codedeploy-agent(38926)]: On Premises config file does not exist or not readable
2018-09-29 10:45:31 ERROR [codedeploy-agent(38926)]: booting child: error during start or run: Errno::ECONNRESET - Connection reset by peer - <internal:prelude>:76:in `__read_nonblock'
<internal:prelude>:76:in `read_nonblock'
/usr/lib/ruby/2.3.0/net/protocol.rb:154:in `rbuf_fill'
/usr/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
/usr/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
/usr/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
/usr/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.10.104/lib/seahorse/client/net_http/patches.rb:29:in `block in new_transport_request'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.10.104/lib/seahorse/client/net_http/patches.rb:26:in `catch'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.10.104/lib/seahorse/client/net_http/patches.rb:26:in `new_transport_request'
/usr/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/usr/lib/ruby/2.3.0/net/http.rb:1156:in `get'
/opt/codedeploy-agent/lib/instance_metadata.rb:52:in `block in http_get'
/usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
/usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
/opt/codedeploy-agent/lib/instance_metadata.rb:51:in `http_get'
/opt/codedeploy-agent/lib/instance_metadata.rb:22:in `region'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:38:in `initialize'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `new'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `runner'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:32:in `block in prepare_run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
```

**Comment by annamataws** [comment] 2018-10-15 17:02
Hi @miradnan,

This seems to be a different problem from the AccessDenied issue. Can you please open a new thread with us so we can track on this issue specifically? Also can you please add your agent config?
I will close this issue as the AccessDeniedException has not specifically been commented about in a while.

Thank you!

**Closed by annamataws** 2018-10-15 17:02 UTC

**Comment by uifreak** [comment] 2020-11-24 23:32
Hi, 

I am seeing the same issue after updating the configuration file to run the agent as non-root (ec2-user), I followed the AWS support page https://aws.amazon.com/premiumsupport/knowledge-center/codedeploy-agent-non-root-profile/ and updated the config, but after the restart, I started getting the error.
