### ISSUE TITLE
Error when trying to do a deployment on debian 10

### ISSUE THREAD

**Issue by btv** [aws/aws-codedeploy-agent#278] opened 2021-02-10 20:28 UTC
I'm trying to troubleshoot why my codedeployments aren't working. I'm using the latest version (1.3.1-1880) on debian 10. The install is fine and systemd's status command shows the service is up. However, when I try to do a local deployment using this command:
`sudo bin/codedeploy-local -l s3://${VALID_PATH_TO_FILE}.zip -t zip`

I end up getting this error:
```
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/appender.rb:139: warning: constant ::Fixnum is deprecated
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/logger.rb:295: warning: constant ::Fixnum is deprecated
Starting to execute deployment from within folder /opt/codedeploy-agent/deployment-root/default-local-deployment-group/d-FE8V8RVBJ-local
See the deployment log at /opt/codedeploy-agent/deployment-root/default-local-deployment-group/d-FE8V8RVBJ-local/logs/scripts.log for more details
Traceback (most recent call last):
	1: from bin/codedeploy-local:123:in `<main>'
bin/codedeploy-local:129:in `rescue in <main>': uninitialized constant InstanceMetadata::InstanceMetadataError (NameError)
```

Sadly, the log file is never written, so I can't get any deeper in troubleshooting this problem. Any help with this would be greatly appreciate. I'm also happy to perform any command you need to help with information gathering.

**Comment by renato-zannon** [comment] 2021-02-16 17:29
I had a similar error when trying to use `codedeploy-local` for local experiments.

In my case, it was caused by [this line](https://github.com/aws/aws-codedeploy-agent/blob/master/bin/codedeploy-local#L129), which  was trying to `rescue` an exception class that is not even defined. I edited the code locally (yay ruby), and was able to see the actual underlying error (a dumb mistake on my part).

What it looks like is that this `InstanceMetadata` module was either removed in a recent version of some dependency, or there is some `require` missing.

**Comment by btv** [comment] 2021-02-16 18:38
@renato-zannon , thanks for the hint. I'll look into more on the machine and see what I can find. I'm not proficient with Ruby, so its a little more of a challenge for me. I figured it was related to not having deployments work at all from the CodeDeploy console, maybe they are different? :man_shrugging:

**Comment by btv** [comment] 2021-02-16 18:51
@renato-zannon Thank you again for the hint, I removed the module from the line and got this error:

```
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:124:in `generate_normal_copy': The deployment failed because a specified file already exists at this location: /${VALID_PATH_TO_VALID_FILE} (RuntimeError)
```
So it looks like the code "eats" the error message that a file that exists on the system can't be overwritten. I reran the same command with the `-b OVERWRITE` flag, and the local deployment works without issue.

Can you recommend any procedure to help debug a problem when codedeploy is initiated from the console? I specifically run my codedeploys to overwrite files that already exist, however, the code deployments never complete. So I'm not sure how to debug this process. Any help would be really appreciated.

**Comment by aekandem** [comment] 2021-03-04 16:31
My issue as well.

**Comment by toshke** [comment] 2021-04-27 13:00
I had this issue as well. Interestingly enough, if binary is started with full path, issue is gone

```
bin/codedeploy-local:129:in `rescue in <main>': uninitialized constant InstanceMetadata::InstanceMetadataError (NameError)
```

however following works just fine

```
if /opt/codedeploy-agent/bin/codedeploy-local -l /opt/last_deployment.zip --type zip -b OVERWRITE; then
    echo "Local deployment successful"
    set -e
    return
  fi
```

**Comment by webkod3r** [comment] 2021-06-29 12:14
Any updates on this? I recently installed the code-deploy agent and I'm getting the same issue

This is the Ruby version I have installed
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

Thanks in advance for your help

**Comment by raghakrk** [comment] 2021-08-29 15:00
I removed `InstanceMetadata::InstanceMetadataError` from [this line](https://github.com/aws/aws-codedeploy-agent/blob/3c39d545b108c29ae46dfe17aa98e518f88f1a14/bin/codedeploy-local#L133), and it worked. Looks like this `InstanceMetadata::InstanceMetadataError` module was removed in a recent version.

**Comment by Eternal21** [comment] 2022-08-30 12:55
I'm having the same issue.  I see people recommending removing some line, but codedeploy-local is a binary file on my server so I can't do it that way.

**Comment by t0shiii** [comment] 2023-03-29 21:10
codedeploy-local error with InstanceMetadata::InstanceMetadataError has been fixed in the upcoming release of the agent version 1.6.0.

Agent source code will be available on GitHub this Friday, March 31st.  Agent installer will be available in all commercial regions by April 7th.

**Comment by mwjones-aws** [comment] 2023-04-05 21:13
CodeDeploy Agent 1.6.0 has been released to most commercial regions as of this comment.

Please track release progress on https://github.com/aws/aws-codedeploy-agent/issues/360

**Closed by mwjones-aws** 2023-04-05 21:13 UTC
Labels: bug, next release candidate
