### ISSUE TITLE
Rubyzip may silently fail to extract all files if there are many of them

### ISSUE THREAD

**Issue by IntractableQuery** [aws/aws-codedeploy-agent#93] opened 2016-12-22 19:11 UTC
Using Jenkins' CodeDeploy plugin with very many files in a directory results in some files missing when they appear on the target instance.

Jenkins is sending over a zip file which is presumably invalid to some extent, but the codedeploy agent cannot detect this because of a `rubyzip` limitation.

The issue is better-described here: https://github.com/rubyzip/rubyzip/issues/266

It may be nice if the codedeploy agent switched to a more resilient library that would warn of this problem.  Jenkins is definitely at blame here since it seems the zip file is invalid, but it does not seem ideal that the codedeploy agent silently completes archive extraction in this case.

**Comment by gaohan137** [comment] 2016-12-27 23:52
Thanks for bringing this up to our attention. We'll create a task to keep track of it and prioritize it accordingly.

**Comment by marius-balteanu** [comment] 2017-11-16 21:41
The issue is still present in the latest version of the plugin.

**Comment by fjhixiuxiu** [comment] 2018-07-25 13:44
+1

**Comment by rohkat-aws** [comment] 2018-07-25 17:35
@marius-balteanu we did try to update to 1.2.1 , But it broke some customer's existing functionalities . So we had to do a rollback , we are looking at options to fix these.

**Comment by mwjones-aws** [comment] 2022-05-31 17:57
Closing as the linked rubyzip issue is also closed

CodeDeploy Agent now depends on [rubyzip ~ 1.3.0](https://github.com/aws/aws-codedeploy-agent/blob/a724d586f0934a0e3d78f40c7bb83ec285730633/codedeploy_agent.gemspec#L17)

**Closed by mwjones-aws** 2022-05-31 17:57 UTC
Labels: bug
