### ISSUE TITLE
Failed deployment DownloadBundle events with error "No such file or directory - getcwd"

### ISSUE THREAD

**Issue by rubashanti** [aws/aws-codedeploy-agent#244] opened 2020-05-21 15:22 UTC
Deployment failed during Download bundle event : with unknown error "No such file or directory - getcwd"

By checking code deploy agent code, This error is returned when the codedeploy agent -ruby code-  is trying to get the working dir, and for some reason it's not finding it, as in the below command :
working_dir = FileUtils.pwd()

https://github.com/aws/aws-codedeploy-agent/blob/27d5b31c72c5004e5683ee1fab1e51d65def75d6/lib/instance_agent/platform/linux_util.rb#L52
This error usually returned when the current directory was deleted. however there was no change on the directory

A restart for the codedeploy agent, and redeploy will fix the issue.

Can you please advise.

**Comment by rubashanti** [comment] 2020-05-21 15:23
similar issue :   https://github.com/aws/aws-codedeploy-agent/issues/120 

OS: Linux

**Comment by jbuehring** [comment] 2020-05-22 17:03
For what it's worth, I experienced this very thing until restarting `codedeploy-agent`.  Baffled for a reason how or why, and certainly hope that doesn't become a pattern.

**Comment by jbuehring** [comment] 2020-05-22 17:23
Another interesting point, if I switched the deployment artifact to `zip` type, it would still emit a bizarre message into `/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log` but would still complete the deployment successfully.

```
[2020-05-22 15:47:12.843] [d-1XY69U1E4]LifecycleEvent - BeforeInstall
[2020-05-22 15:47:12.844] [d-1XY69U1E4]Script - deploy/prepare_deploy.sh
[2020-05-22 15:47:12.847] [d-1XY69U1E4][stderr]shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

Truly bizarre.

**Comment by brblck** [comment] 2020-05-27 00:58
If I had to guess I would say that there's something incorrect in your installation of Ruby preventing it from interacting with the underlying native C libraries powering `FileUtils`. It's also possible that your file system encoding could be causing problems with Ruby's ability to read the working directory.

@rubashanti to isolate the problem, can you confirm run the result of the following commands under the same user you're attempting to run the agent under?

```bash
echo $LANG
echo $LC_CTYPE

ruby -v
ruby -e "require 'fileutils'; puts FileUtils.pwd()"
ruby -e "puts Encoding.find('filesystem')"
```

**Comment by Israphel** [comment] 2020-05-27 14:15
Well in my case I use Amazon Linux 2 and I just install ruby and codedeploy agent from: https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install

I would assume than Amazon Linux 2 Ruby is ok.

`[root@ip-10-4-0-168 ~]# echo $LANG
en_US.UTF-8

[root@ip-10-4-0-168 ~]# echo $LC_CTYPE

[root@ip-10-4-0-168 ~]# ruby -v
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

[root@ip-10-4-0-168 ~]# ruby -e "require 'fileutils'; puts FileUtils.pwd()"
/root

[root@ip-10-4-0-168 ~]# ruby -e "puts Encoding.find('filesystem')"
UTF-8`

**Comment by Israphel** [comment] 2020-06-05 15:58
Today the issue happened again to me. Only in us-west-2 in a multiregion pipeline, even tho the artifact is exactly the same.

**Comment by brblck** [comment] 2020-08-28 22:45
Duplicate of https://github.com/aws/aws-codedeploy-agent/issues/255

**Closed by brblck** 2020-08-28 22:45 UTC
Labels: waiting for info

**Comment by TomZhuPlanetart** [comment] 2023-11-30 08:51
It's not a duplicate issue of #255,  the error is different. 

Our production server encountered this issue today. 


```
$ sudo lsof -p 650
COMMAND PID USER   FD      TYPE             DEVICE  SIZE/OFF      NODE NAME
ruby    650 root  cwd       DIR              259,3         6 205521082 /opt/codedeploy-agent/deployment-root/bc3648ae-4408-4e76-9ff2-66603cd21741/d-0G43URW03/deployment-archive (deleted)
ruby    650 root  rtd       DIR              259,3       257        96 /
ruby    650 root  txt       REG              259,3     68480  13134719 /usr/bin/ruby
```

If we check the `codedeploy-agent` with `lsof`,  we can find the `cwd` has changed to the directory of  a past deployment which has been deleted.  This deployment was created 3 days ago.  

Version: 1.6.0-49

Restarting the codedeploy service resolved the problem.
