### ISSUE TITLE
Does not run scripts with providing the environment the runas user would expect

### ISSUE THREAD

**Issue by gentaro-sakamoto** [aws/aws-codedeploy-agent#73] opened 2016-07-18 14:43 UTC

**Comment by Jmcfar** [comment] 2016-08-17 20:05
Hi,

Can you provide some more information around what environment you are expecting to see within your script?

**Comment by Ethanjfobrien** [comment] 2016-11-30 11:52
for example if the runas user has nodejs installed, when the agent runs a script as that user it says "npm command not found". If the script is modified to provide the path to npm it then trys to run npm from the root user profile and hasn't sufficient permissions

**Comment by annamataws** [comment] 2018-08-03 22:23
Related to https://github.com/aws/aws-codedeploy-agent/issues/111

**Comment by mwjones-aws** [comment] 2022-06-07 17:25
I think this is a duplicate of #191. Please re-open if this isn't the case.

**Closed by mwjones-aws** 2022-06-07 17:25 UTC
Labels: question
