### ISSUE TITLE
CodeDeploy-Agent falsely reports a successful install via SSM when using Ubuntu 22.04 and proceeds to fail

### ISSUE THREAD

**Issue by hparadiz** [aws/aws-codedeploy-agent#321] opened 2022-06-02 21:58 UTC
Just tried to install CodeDeploy-Agent on a fresh 22.04 box and it fails silently.

This is because 22.04 comes with Ruby 3.x instead of 2.x

**Comment by mwjones-aws** [comment] 2022-06-07 17:08
Hello,

Ubuntu 22 is not supported by the CodeDeploy agent yet. Here's a [list of the operating systems we do support today](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html) 

Can you tell me more about the silent failure? Did SSM distributor say that CodeDeploy Agent installed successfully?

**Comment by mwjones-aws** [comment] 2022-06-07 17:11
Duplicate of #301

**Closed by mwjones-aws** 2022-06-07 17:11 UTC

**Comment by hparadiz** [comment] 2022-06-07 17:29
@mwjones-aws 

> Can you tell me more about the silent failure? Did SSM distributor say that CodeDeploy Agent installed successfully?

Yup. That's exactly what happened.
