### ISSUE TITLE
Allow user to specify ruby version to run the agent as

### ISSUE THREAD

**Issue by bradleyjames** [aws/aws-codedeploy-agent#90] opened 2016-12-01 23:41 UTC
bin/codedeploy-agent is unnecessarily complex and creates odd failure scenarios.

1.  I updated my installed version of ruby to 2.3.3.  Because the script has 2.3.1 hard coded as the maximum supported version the script tried to find a different ruby and chose a much older one which was core dumping when I attempted to start the agent.

2.  Even if the script found another ruby that ruby won't necessarily the ruby I want to run the agent with.  Randomly choosing a ruby isn't helpful and is un *nix like.

My request is to check for the existence of an environment variable specifying the ruby to use.  If it doesn't exist use the ruby the script is ran with.  No guessing.

**Comment by gdeblina** [comment] 2017-02-14 21:25
Thank you for the request, we will add it to our feature request list.

**Comment by charusat09** [comment] 2019-07-16 06:58
@gdeblina if this feature is already merged to master then, this issue needs to be closed.

**Comment by mwjones-aws** [comment] 2022-06-07 17:18
Duplicate of #301

**Closed by mwjones-aws** 2022-06-07 17:18 UTC
Labels: feature-request
