### ISSUE TITLE
Debian package ignores /usr/sbin/policy-rc.d, always starts daemon

### ISSUE THREAD

**Issue by ktheory** [aws/aws-codedeploy-agent#44] opened 2015-12-28 22:10 UTC
When creating a base Ubuntu AMI with the codedeploy agent pre-installed, I'd like to be able to install the codedeploy agent w/out the daemon starting.

After installing on the base AMI, I need to manually stop the daemon and clean up log files.

The idiomatic way to handle whether to start a service during installation is to use [`invoke-rc.d`](https://people.debian.org/~hmh/invokerc.d-policyrc.d-specification.txt).

Instead of invoking `service codedeploy-agent {start,stop}` in `postinst`/`prerm`, use `invoke-rc.d`:

```
# In postinst:
invoke-rc.d codedeploy-agent start
```

See the nginx package's postinst script for example.

`invoke-rc.d` runs `/usr/sbin/policy-rc.d` to determine whether a service should be started.

I looked for how to make this change myself in a pull request, but I couldn't figure out how the controls scripts in the deb package is generated from this repo.

**Comment by Jmcfar** [comment] 2016-01-05 20:51
Hi,

Thanks for the feature request. I've added it to our backlog. 

Unfortunately the code responsible for generating the control scripts is not in the GitHub project and is part our internal release process.

**Comment by jinty** [comment] 2017-02-09 15:46
+1 I've also hit this, it is quite irritating. Fortunately unpacking using dpkg-deb and editing the postinst seems to work.

**Comment by mwjones-aws** [comment] 2022-06-07 17:49
Duplicate of #315

**Closed** 2022-06-21 17:34 UTC
Labels: enhancement
