### ISSUE TITLE
Support for Ubuntu 22.04 / ruby 3.x

### ISSUE THREAD

**Issue by sebastianreloaded** [aws/aws-codedeploy-agent#319] opened 2022-05-03 14:50 UTC
The codedeploy agent still needs ruby 2.x: https://github.com/aws/aws-codedeploy-agent/blob/a724d586f0934a0e3d78f40c7bb83ec285730633/bin/install#L215-L217

Ubuntu 22.04 only support ruby 3.x and OpenSSL 3.0. This also means it is not possible to install ruby 2.x on Ubuntu 22.04.

So atm there is no way to use Ubuntu 22.04 on AWS with codedeploy.

**Comment by mwjones-aws** [comment] 2022-05-03 17:05
Hi, resolving as duplicate of https://github.com/aws/aws-codedeploy-agent/issues/301

We'll track this issue there.

**Closed by mwjones-aws** 2022-05-03 17:05 UTC

**Comment by RodrigoAlejandroBP** [comment] 2022-08-05 20:42
Still no news on this?
