### ISSUE TITLE
Codedeploy agent failed when aws-sdk-core is installed on system with version 2.7.0

### ISSUE THREAD

**Issue by Cicatrice** [aws/aws-codedeploy-agent#101] opened 2017-01-24 14:58 UTC
Hello,

I am using latest version of codedeploy on `us-east-1` region, 
```
root@ip-10-0-0-197:~# dpkg -l | grep codedeploy
ii  codedeploy-agent                  1.0-1.1067                          all          CodeDeploy instance agent is responsible for doing the actual work of deploying software on an EC2 instance.
```

and I have the following issue when the agent start : 
```
2017-01-24 14:25:39 ERROR [codedeploy-agent(19086)]: Plugin codedeploy could not be loaded: Unable to activate codedeploy-commands-1.0.0, because aws-sdk-core-2.7.0 conflicts with aws-sdk-core (~> 2.6.11).
2017-01-24 14:25:39 ERROR [codedeploy-agent(19086)]: booting child: error during start or run: Gem::ConflictError - Unable to activate codedeploy-commands-1.0.0, because aws-sdk-core-2.7.0 conflicts with aws-sdk-core (~> 2.6.11) - /usr/lib/ruby/2.3.0/rubygems/specification.rb:2286:in `raise_if_conflicts'
```

It seems that codedeploy-agent embbed its own version of aws-sdk-core, but try to load the system version if it exists. Any idea ?

Many thanks

**Comment by eric-tucker** [comment] 2017-03-16 18:12
Come on guys.  This cat/mouse game between SDK versions is ridiculous.  You need a long term solution that doesn't break every time the Ruby SDK is updated.

**Comment by odoisneau** [comment] 2017-04-04 16:22
Did anyone find a clean solution to this?  I am having the same issue.

**Comment by Cicatrice** [comment] 2017-04-04 16:30
Migrate to Microsoft Azure.

Just kidding (for the moment). My solution is to downgrade the AWS Ruby SDK on target machine and lock its version to the latest supported by CodeDeploy agent (2.6.x). Hopefully I don't need features from 2.7 yet.

I opened this ticket a few months ago, it's a shame that no AWS people came to reply.

**Comment by odoisneau** [comment] 2017-04-04 16:57
yeah kind of a pain.  we use 2.4 for our app so annoying to have 2 versions just for this.  I guess I can change the startup scripts to use old ruby version.  Thanks for the feedback.

**Comment by jackdpeterson** [comment] 2017-06-05 06:21
A bit frustrating here to have CodeDeploy break here locally. This tool is awfully brittle for a dev-ops tool. Can CodeDeploy be rewritten in the same tooling that the AWS CLI is written in (Python)  ... or Perhaps Java like the rest of the AWS infrastructure to reduce dependency bloat?

**Comment by zaiddabaeen** [comment] 2018-05-31 09:11
I had almost the same issue this morning, one of our servers was undeployable to due to
cannot load such file -- aws-sdk-core/s3
Even though it has been working fine for a year.

I had a frustrated phase, so I bought 23 servers from Google Shopping, removed the sales employees desks, I am currently building racks in the office.

(P.S: Recreating the instance did the job)

**Comment by annamataws** [comment] 2018-08-02 18:17
Duplicate of https://github.com/aws/aws-codedeploy-agent/issues/60
Closing issue. Will update #60

**Closed by annamataws** 2018-08-02 18:17 UTC
Labels: bug, feature-request
