### ISSUE TITLE
Two deployments in the same directory: the second one fails

### ISSUE THREAD

**Issue by tlacroix** [aws/aws-codedeploy-agent#185] opened 2018-08-29 20:18 UTC
We are using Ubuntu 18.04, and are cloning the github repository's `master` branch.

We currently have two deployments in two separate directories:
- `/var/www/api`
- `/var/www/angular`

We can't seem to be able to deploy both in `/var/www` with the new version of the agent, while it works fine with the previous one.

The deployment will fail during the install stage after less than a second if /var/www is not completely empty.

The error code it returns is: `Unknown error,   
Directory not empty @ dir_s_rmdir - /var/www`

We were previously using Ubuntu 16.04 with the CodeDeploy agent located here: s3://aws-codedeploy-us-east-1/latest/install -- and it works fine with two deployment in `/var/www`.

Version `v1.0-1518` on github seems to work properly on Ubutun 18.04, and we can deploy both applications in `/var/www`. We only really have this problem with the `master` branch.

Our environment is pretty standard (Vanilla Ubuntu 18.04, with a few standard packages installed, such as nginx, php7.2-fpm, etc.)

Steps to reproduce:
- Deploy api: success
- Deploy angular: error
- Deploy angular: error
- Delete /var/www
- Deploy angular: success
- Deploy api: error
- Deploy api: error

Our `appspec.yml` goes as follow (it's the same for the angular project, but with `/var/www/angular` instead):

```
# http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html

version: 0.0

os: linux

files:
   - source: /
     destination: /var/www/api

permissions:
  - object: /var/www/api
    pattern: "**"
    owner: root
    group: www-data
    mode: 775
    type:
      - directory
  - object: /var/www/api
    pattern: "**"
    owner: root
    group: www-data
    mode: 664
    type:
      - file
```

**Comment by jackdpeterson** [comment] 2018-08-30 19:33
From my experience using CodeDeploy you should not attempt to deploy two applications simultaneously to the same instance -- that approach is operating outside of the intended design of AWS CodeDeploy. 

The are two paths forward:
Option one: deploy the two applications out into two separate instance(s) or autoscaling groups that have been downsized to each applications requirements now that they are independent. Each application must live on its own, independent of each other (in terms of codedeploy processes) because it'll die at the most inconvenient time if you try to do things simultaneously.  This can be easily reproduced by setting up two applications on an autoscaling group and scaling in a new instance. Boom, it'll fail because only one can run at at a time.

Option two: If you do need to deploy two applications onto the same instance (e.g., they have some shared memory / local FS dependency) then create a single code-deploy project that has the two applications merged together into a single artifact that can be deployed as one unit rather than two.

**Comment by rohkat-aws** [comment] 2018-08-30 19:59
@jackdpeterson we support concurrent deployment , the only thing we ask is that the instance should be in 2 diff deployment groups

**Comment by tlacroix** [comment] 2018-08-30 20:14
@jackdpeterson The deployment are not simultaneously performed, they are done one after the other. But I think you mean two deployments on the same instance, simultaneous or not.

Also, looks like trapping the error in `lib/instance_agent/plugins/codedeploy/install_instruction.rb` line 215 resolves our issue. There's a comment with a TODO about it.

```
              # TODO (AWSGLUE-713): handle the exception if the directory is non-empty;
              # this might mean the customer has put files in this directory and we should
              # probably ignore the error and move on
              FileUtils.rmdir(@file_path) rescue  StandardError
```

**Comment by jackdpeterson** [comment] 2018-08-30 23:58
oh wow @rohkat-aws -- I didn't know it actually could do two different applications on the same instance -- I ran into numerous issues and at the time when I was researching that it looked like it sounded like a no-no. Just so I'm clear -- if you have two applications:
Application 1, com.example.application1
Application 2, named com.example.application2

Let's assume both applications have two deployment groups with the same name, "beta", and "production". Are you saying that the names of the deployment groups need to be different (e.g., both can't share the same name) ... or something else?

https://docs.aws.amazon.com/codedeploy/latest/userguide/troubleshooting-auto-scaling.html#troubleshooting-multiple-depgroups

seems to be where you're coming from but I want to ensure my understanding is correct so as to prevent future confusion on my end.

**Comment by tlacroix** [comment] 2018-09-03 21:50
@jackdpeterson We've been deploying two applications on the same instances for years. The only thing you can't do is deploy two applications simultaneously (as in the two deployments installing at the same time) on the same deployment group. But you can run them one after the other without any problem, it has always worked for us until now. 

We added a manual `rescue StandardError` where I indicated to solve the problem in the meantime.

**Comment by geodeveloper** [comment] 2018-10-24 00:07
Same problem with Ubuntu 18.04

Error code
`UnknownError`
Script name

Message
`Directory not empty @ dir_s_rmdir - /home/ubuntu/app/bootstrap/cache`

In order to make it work again, I have to delete the `app` folder manually and re-deploy which is annoying.

**Comment by teeli** [comment] 2018-11-01 12:46
I'm now getting the same error as @geodeveloper. Including the the path in the comment, so I guess we're both deploying Laravel applications.

This started happening when I updated my base AMI to Ubuntu 18.04.

**Comment by knightcode** [comment] 2018-11-03 21:52
Also having this issue. Our AfterInstall hook causes the creation of additional files, so that a subsequent deployment fails with this error

**Comment by stevethomas** [comment] 2018-11-19 06:54
I encountered this error right after upgrading to ubuntu 18 as well - although I am not trying to run 2 applications.

`Directory not empty @ dir_s_rmdir - /home/ubuntu/web`

As far as I can tell, Code Deploy no longer wants to delete `vendor` and `node_modules` whereas it wasn't a problem before on Ubuntu 14.

**Comment by joshdutcher** [comment] 2018-12-04 21:46
Same problem here. CodeDeploy is not removing the `vendor` folder in my php application which is throwing the same error.

**Comment by notori0us** [comment] 2018-12-05 17:29
:( Also having this issue on Ubuntu 18.04. Please provide guidance

**Comment by annamataws** [comment] 2018-12-06 23:18
Hi,
We are still looking into it.
Thank you

**Comment by kennyjwilli** [comment] 2018-12-12 00:12
I have also hit this with Ubuntu 18.04. Running with Ubuntu 16.04 fixed it.

**Comment by spilist** [comment] 2019-01-01 13:36
When installing ruby in ubuntu 18.04, ruby version `2.5.x` is installed by default.

Before ruby 2.5(i.e., 2.4.3), `FileUtils.rmdir` [silently fails when the target directory is not empty](https://ruby-doc.org/stdlib-2.4.3/libdoc/fileutils/rdoc/FileUtils.html#method-c-rmdir), so the non-empty directories in cleanup file are not removed. 

But the implementation of `FileUtils.rmdir` is [changed in ruby 2.5](https://ruby-doc.org/stdlib-2.5.0/libdoc/fileutils/rdoc/FileUtils.html#method-c-rmdir) so that it doesn’t rescue from `Errno::ENOTEMPTY` any more, which generates failures in deployment.

You may refer to [the PR](https://github.com/what-is-quality/aws-codedeploy-agent/pull/9) referenced above which I'll submit here soon. Although I'm wondering what time this would be accepted and merged.

**Comment by dlo** [comment] 2019-02-11 21:17
I'm getting this error with a single deployment and one directory. Seems like this fix should really be prioritized.

**Comment by vijayshukla30** [comment] 2019-02-12 15:45
Any solution on this. I am getting the error when redeploying the application.

**Comment by dlo** [comment] 2019-02-12 15:46
The one thing I did that appeared to work was to completely uninstall the CodeDeploy agent and then I had to wipe the /opt/codedeploy directory as well. If you leave that directory around, future deploys will fail after a reinstallation.

**Comment by renatoaloi** [comment] 2019-02-12 20:06
> 
> 
> The one thing I did that appeared to work was to completely uninstall the CodeDeploy agent and then I had to wipe the /opt/codedeploy directory as well. If you leave that directory around, future deploys will fail after a reinstallation.

It works! Thank you @dlo ! For those are curious about the command to unninstall CodeDeploy agent, here it comes:
``` 
$ sudo dpkg --purge codedeploy-agent
```
Then delete the ```/opt/codedeploy-agent``` directory

and voilá!

Another thing I did was change from root to ubuntu user at appspec.yml file, as follows:

```
version: 0.0
os: linux
files:
  - source: xxx.file
    destination: /home/ubuntu/xxx-app
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 30000
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 30000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server
      timeout: 30000
      runas: ubuntu
```

**Comment by vijayshukla30** [comment] 2019-02-13 06:05
Thanks @renatoaloi  and @dlo . It works.

**Comment by dlo** [comment] 2019-02-13 11:03
@renatoaloi @vijayshukla30 I'm kind of surprised my solution actually works for others! Now the next step would just be somehow force-wiping this directory on reinstallation or forcing it to delete when running the `$ sudo dpkg --purge codedeploy-agent` command.

Thanks @renatoaloi for spelling our the full commands, etc. :)

**Comment by dlo** [comment] 2019-02-20 16:03
@drafie To clarify, if deployments are failing, you can just delete that specific folder and there will be no other issues? Have you tested thoroughly?

I'm afraid that skipping the uninstall step will leave certain files around that CodeDeploy looks for to enable continuity between deploys. It makes me nervous to think it may be using old data.

**Comment by renatoaloi** [comment] 2019-02-21 19:40
Hi guys! I've found alternative solution to this issue...

From BeforeInstall section, in the appspec.yml file, I've added the following script

```
#!/bin/bash

cd /home/ubuntu/my-app-dir
rm -rf manage.py requirements.txt my-project-folder my-app-folder
```

It grants all folders being removed before the actual installation.

That solved for good my problem. I hope it helps you too.

**Comment by Samuell1** [comment] 2019-03-14 13:52
Same issue with OctoberCMS and Ubuntu 18.

```
Directory not empty @ dir_s_rmdir - /var/www/html/storage/framework
```

**Comment by tlacroix** [comment] 2019-03-14 14:27
Since a lot of people seem to be experiencing the same issue, I just pushed a PR based on the patch we've successfully been using in development and production since August 2018 to go around this (the `rescue StandardError` addition I mentioned in an earlier comment).

**Comment by Samuell1** [comment] 2019-03-14 15:34
@tlacroix Thats amazing! Can i somehow use your PR change in my server? To test it out?

**Comment by spilist** [comment] 2019-03-14 15:36
@tlacroix @Samuell1 You may use my previous PR in this thread(#201) instead. Folks said it's working well in their servers.

**Comment by Samuell1** [comment] 2019-03-14 16:44
Thanks! @spilist but question is how to update it my server? Its there a way to automatize it or i need to update one by one?

**Comment by spilist** [comment] 2019-03-19 00:15
@Samuell1 Unfortunately I currently have no idea for automating it. Sorry for the late response.

**Comment by Samuell1** [comment] 2019-03-19 07:33
@spilist i think i found a way with AMI it can work for now

**Comment by johnsonch** [comment] 2019-04-16 12:28
@Samuell1 how did you get it automated?

**Comment by Samuell1** [comment] 2019-04-16 13:28
@johnsonch installed aws-codeploy on EC2 and updated file with fix and then created Image and reused that in Launchtemplates etc

**Comment by notori0us** [comment] 2019-06-04 18:37
so... is this _still_ an issue?

**Comment by johnsonch** [comment] 2019-06-05 13:45
I had to change the deploy location and update my scripts to manually
remove the previous build.

So I would assume it's still an issue and I just found work around.

*Chris Johnson * | Johnson*CH*, LLC | 608.320.5190

**Comment by hdm** [comment] 2019-08-26 05:26
If anyone else hits this and gets stuck (all new deployments failing), removing the `*-cleanup` files in `/opt/codedeploy-agent/deployment-root/deployment-instructions/` allows deployments to run again.

**Comment by hanuor** [comment] 2019-09-17 04:40
For anyone who's still facing the issue `Directory not empty @ dir_s_rmdir - /var/www" on Ubuntu 18.04`
For the first time - 
Step 1 - Delete the cleanup files as commented by @hdm earlier.
Step 2 - When creating a deployment, under the Additional deployment behavior settings tab, check the 'Retain the content' checkbox.

For the case when you wanna redeploy again - 
Ignore Step 1 and follow Step 2.

Hope it works!

**Comment by simples1** [comment] 2020-02-19 20:15
> If anyone else hits this and gets stuck (all new deployments failing), removing the `*-cleanup` files in `/opt/codedeploy-agent/deployment-root/deployment-instructions/` allows deployments to run again.

Worked great!!!

**Closed** 2020-02-27 23:14 UTC
Labels: bug

**Comment by h3r2on** [comment] 2020-03-17 19:56
this patch works great, is there an eta on when will this get push out in an official release

**Comment by tlacroix** [comment] 2020-03-18 18:35
> this patch works great, is there an eta on when will this get push out in an official release

Another patch that works has been merged (see link below). I don't know if it's been pushed in an official release yet though.

https://github.com/aws/aws-codedeploy-agent/issues/185

**Comment by WhiteyDude** [comment] 2020-03-26 05:28
I've built a quick hack fix for this until the official release push is done:

https://gist.github.com/WhiteyDude/fd8744440a021b3bb2d1b6cb40ff93ac

**Comment by bonifaciokid** [comment] 2021-06-17 06:53
I still got this error. It will only deploy if I will delete the folder in the instance.
