### ISSUE TITLE
Codedeploy not getting installed on Ubuntu focal because of ruby 2.7

### ISSUE THREAD

**Issue by shivansh931** [aws/aws-codedeploy-agent#243] opened 2020-04-27 20:38 UTC
install: line 9: class: command not found
install: line 11: syntax error near unexpected token `('
install: line 11: `    undef_method m unless m =~ /(^__|^send$|^object_id$)/'

**Comment by brblck** [comment] 2020-05-26 20:27
Closing as duplicate of https://github.com/aws/aws-codedeploy-agent/issues/239.

**Closed by brblck** 2020-05-26 20:27 UTC
Labels: duplicate
