### ISSUE TITLE
Report completed deployment

### ISSUE THREAD

**Issue by viraptor** [aws/aws-codedeploy-agent#220] opened 2019-07-12 00:53 UTC
Currently there are log line produced for each stage of the deployment lifecycle, however there is nothing reported at the end of deploy. It would be great to get a message like:
```
[2019-07-11 16:33:52.893] [d-BO8Z62ZIB] Deployment complete
```

Given the last stage of the deploy is often "verify", I've run into logs ending like this:
```
[2019-07-11 16:33:52.787] [d-BO8Z62ZIB]Script - remote_scripts/validate_service.sh
[2019-07-11 16:33:52.893] [d-BO8Z62ZIB][stdout]Waiting for http service
```
From which you can't really tell whether the deployment completed, or is it still hanging on the waiting step.

This can be of course worked around by adding completion messages to all scripts, but given this requires extra attention in every single deploy process, could we get one from the codedeploy agent instead?

**Comment by t0shiii** [comment] 2022-10-04 17:51
Closing as a duplicate of #270

**Closed by t0shiii** 2022-10-04 17:51 UTC
Labels: enhancement, needs triage
