### ISSUE TITLE
CodeDeploy agent is not supporting ruby v3.0.1

### ISSUE THREAD

**Issue by charusat09** [aws/aws-codedeploy-agent#301] opened 2021-07-20 07:02 UTC
When I tried to install codedeploy agent on my server:
```
$ bundle install
Fetching gem metadata from http://rubygems.org/...........
Resolving dependencies...
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby

    aws_codedeploy_agent was resolved to 1.3.2, which depends on
      Ruby (~> 2.0)

Ruby (~> 2.0), which is required by gem 'aws_codedeploy_agent', is not
available in the local ruby installation
$ ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
```

We are using Rails v6 and Ruby v3.0.1.

**Comment by rromanchuk** [comment] 2021-09-01 00:14
@charusat09  i'm going to go down the rabbit hole fork and bump this project 3.0.1  and see how far i can get in my staging env

**Comment by rromanchuk** [comment] 2021-09-01 00:18
tracking here https://github.com/rromanchuk/aws-codedeploy-agent/pull/1

**Comment by OmriSama** [comment] 2022-04-04 17:57
So the agent STILL doesn't support Ruby 3?

**Comment by rromanchuk** [comment] 2022-04-04 19:24
@OmriSama i've been using ansible/system manager to provision this as a standard systemd service using the same rbenv ruby 3.1.0 environment the rest of my production uses, without an issue. Wanted to make sure there were no major runtime blockers for the agent source on its own. a lot of the complexity here is just cross platform distribution  

Another motivation was to get rid of the system ruby dependency, which really is just minor changes to the service config  https://github.com/aws/aws-codedeploy-agent/blob/master/init.d/codedeploy-agent.service

Let me at least publish an example of what i am doing. I was thinking about maybe how adding a new install type https://github.com/aws/aws-codedeploy-agent/blob/master/bin/install#L478 to offer rbenv/custom install, which is really just a user supplied path, instead of relying on system packagers, which will consistently always drag many versions behind a modern ruby deployment.

**Comment by OmriSama** [comment] 2022-05-03 16:40
CodeDeploy should really embed its own Ruby, like Chef does.

**Comment by philstrong** [comment] 2022-05-05 01:57
We should look into this

**Comment by fleaz** [comment] 2022-05-12 10:10
It's "funny" that every two years I end up in this issue tracker because the Codedeploy agent is apparently an unloved child to AWS. Release of 18.04: broken (#158), Release of 20.04: broken (#264), Release of 22.04: broken (this issue).

I really can't wrap my head around how such a fundamental* piece of software can be such a trash fire for years when released by a multi-billion dollar company. This repo once again hasn't seen a commit for 10 months now :(

Sorry for all the negativity in most of my comments in this repo, but it's really frustrating when you have to work with this every day and run into the same walls every Ubuntu release :(

* Or am I one of the last 5 persons on earth that aren't using containers and still rely on Codedeploy?

**Comment by OmriSama** [comment] 2022-05-12 15:45
> It's "funny" that every two years I end up in this issue tracker because the Codedeploy agent is apparently an unloved child to AWS. Release of 18.04: broken (#158), Release of 20.04: broken (#264), Release of 22.04: broken (this issue).
> 
> I really can't wrap my head around how such a fundamental* piece of software can be such a trash fire for years when released by a multi-billion dollar company. This repo once again hasn't seen a commit for 10 months now :(
> 
> Sorry for all the negativity in most of my comments in this repo, but it's really frustrating when you have to work with this every day and run into the same walls every Ubuntu release :(
> 
> * Or am I one of the last 5 persons on earth that aren't using containers and still rely on Codedeploy?

You are not alone, my friend. 

Although, you could still be using CodeDeploy even if you did use containers!

**Comment by rromanchuk** [comment] 2022-05-12 23:53
@philstrong I was thinking about maybe a BYOB(inary) solution, something simple like passing `--binary-path`. The cross platform requirements are what makes this challenging.  Apt and Amazon Linux 2 are always going to be 5 years behind, so there would never be a case where the daemon would be able to use the same production ruby binary.

**Comment by alexekorn** [comment] 2022-05-15 23:08
I haven't actually verified a full deployment using the agent, but I was able to get it installed, using [a similar process to 20.04's required installation](https://github.com/aws/aws-codedeploy-agent/issues/239#issuecomment-622630774), where you repackage the .deb to require ruby3.0 instead of 2.x:

```
cd /tmp
wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/releases/codedeploy-agent_1.3.2-1902_all.deb
mkdir codedeploy-agent_1.3.2-1902_ubuntu22
dpkg-deb -R codedeploy-agent_1.3.2-1902_all.deb codedeploy-agent_1.3.2-1902_ubuntu22
sed 's/Depends:.*/Depends:ruby3.0/' -i ./codedeploy-agent_1.3.2-1902_ubuntu22/DEBIAN/control
dpkg-deb -b codedeploy-agent_1.3.2-1902_ubuntu22/
dpkg -i codedeploy-agent_1.3.2-1902_ubuntu22.deb
```

And afterward, voila:
```
$ systemctl list-units --type=service | grep codedeploy
  codedeploy-agent.service                       loaded active running LSB: AWS CodeDeploy Host Agent
```

(It sure feels like CodeDeploy is abandoned/deprecated. Or, if not, it's been the biggest issue for our Ubuntu upgrades the last two times. Given this experience, I'll be looking for a less janky way to deploy.)

**Comment by sacckey** [comment] 2022-05-17 10:36
@alexekorn 
Thank you very much.
In addition to the above command, I was able to deploy by executing the following command.
```
$ sudo gem install webrick
```

**Comment by moosthuizen42** [comment] 2022-05-18 11:51
Expanding on the answer above, here is a full script. Massive thank you to @alexekorn. This script essentially replaces all the intructions in the official documentation ([Install the CodeDeploy agent for Ubuntu Server](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-ubuntu.html)).

```
#!/bin/bash
# This installs the CodeDeploy agent and its prerequisites on Ubuntu 22.04.

sudo apt-get update
sudo apt-get install ruby-full ruby-webrick wget -y
cd /tmp
wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/releases/codedeploy-agent_1.3.2-1902_all.deb
mkdir codedeploy-agent_1.3.2-1902_ubuntu22
dpkg-deb -R codedeploy-agent_1.3.2-1902_all.deb codedeploy-agent_1.3.2-1902_ubuntu22
sed 's/Depends:.*/Depends:ruby3.0/' -i ./codedeploy-agent_1.3.2-1902_ubuntu22/DEBIAN/control
dpkg-deb -b codedeploy-agent_1.3.2-1902_ubuntu22/
sudo dpkg -i codedeploy-agent_1.3.2-1902_ubuntu22.deb
systemctl list-units --type=service | grep codedeploy
sudo service codedeploy-agent status
```

You should see this when installation has been successfully completed:

![output](https://user-images.githubusercontent.com/36568323/169031920-c1769d9a-e42d-43f3-a37a-117579437046.png)


Working on Ubuntu 22.04 (ami-09d56f8956ab235b3) deployed on a `t3.nano` instance in N. Virginia.

**Comment by OmriSama** [comment] 2022-05-31 21:01
Update to CodeDeploy agent has been postponed to end of June: https://github.com/aws/aws-codedeploy-agent/issues/318#issuecomment-1142632801

**Comment by wbelk** [comment] 2022-06-18 16:32
@moosthuizen42 thanks for this, worked perfectly, had a time finding this

**Comment by mpdude** [comment] 2022-06-29 19:27
So there is no code issue/compatibility issue per se, only the question of how to package this to make it installable on different Debian/Ubuntu/… distros?

**Comment by mpdude** [comment] 2022-06-29 19:55
Where/how does packaging of the Debian/Ubuntu packages happen?

**Comment by trunov** [comment] 2022-08-10 12:02
@alexekorn Thank you so much ! I've been struggling with this for one day.

**Comment by philstrong** [comment] 2022-10-11 07:02
Agent 1.4 will be out soon. The version of the agent following that will
support Ruby 3. This may need a major version bump to agent 2.0 as it will
not support Ruby 2. The team will also look into including our own version
of isolated Ruby.

The agent is anything but abandoned. We now have a dedicated team just
focused on it and host deployments.

**Comment by yasirtrimulabs** [comment] 2022-10-24 16:54
Thanks @moosthuizen42 

For anyone who doesn't know how to do anything like me, here's the noob steps:

1. Enter the following command:
   `touch install-code-deploy-ubuntu22-ec2.sh`
2. Enter the following command:
   `cat > install-code-deploy-ubuntu22-ec2.sh`
3. Paste the following:
   ```
   #!/bin/bash
   # This installs the CodeDeploy agent and its prerequisites on Ubuntu 22.04.
   sudo apt-get update
   sudo apt-get install ruby-full ruby-webrick wget -y
   cd /tmp
   wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/releases/codedeploy-agent_1.3.2-1902_all.deb
   mkdir codedeploy-agent_1.3.2-1902_ubuntu22
   dpkg-deb -R codedeploy-agent_1.3.2-1902_all.deb codedeploy-agent_1.3.2-1902_ubuntu22
   sed 's/Depends:.*/Depends:ruby3.0/' -i ./codedeploy-agent_1.3.2-1902_ubuntu22/DEBIAN/control
   dpkg-deb -b codedeploy-agent_1.3.2-1902_ubuntu22/
   sudo dpkg -i codedeploy-agent_1.3.2-1902_ubuntu22.deb
   systemctl list-units --type=service | grep codedeploy
   ```

4. Press `ctrl + d`
5. Enter the following command:
   `chmod u+x install-code-deploy-ubuntu22-ec2.sh`
6. Enter the following command:
   `./install-code-deploy-ubuntu22-ec2.sh`
7. Enter the following command:
   `sudo service codedeploy-agent status`

**Comment by itswodud** [comment] 2022-12-01 09:10
thank you

**Comment by itswodud** [comment] 2022-12-01 09:10
> Expanding on the answer above, here is a full script. Massive thank you to @alexekorn. This script essentially replaces all the intructions in the official documentation ([Install the CodeDeploy agent for Ubuntu Server](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-ubuntu.html)).
> 
> ```
> #!/bin/bash
> # This installs the CodeDeploy agent and its prerequisites on Ubuntu 22.04.
> 
> sudo apt-get update
> sudo apt-get install ruby-full ruby-webrick wget -y
> cd /tmp
> wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/releases/codedeploy-agent_1.3.2-1902_all.deb
> mkdir codedeploy-agent_1.3.2-1902_ubuntu22
> dpkg-deb -R codedeploy-agent_1.3.2-1902_all.deb codedeploy-agent_1.3.2-1902_ubuntu22
> sed 's/Depends:.*/Depends:ruby3.0/' -i ./codedeploy-agent_1.3.2-1902_ubuntu22/DEBIAN/control
> dpkg-deb -b codedeploy-agent_1.3.2-1902_ubuntu22/
> sudo dpkg -i codedeploy-agent_1.3.2-1902_ubuntu22.deb
> systemctl list-units --type=service | grep codedeploy
> sudo service codedeploy-agent status
> ```
> 
> You should see this when installation has been successfully completed:
> 
> ![output](https://user-images.githubusercontent.com/36568323/169031920-c1769d9a-e42d-43f3-a37a-117579437046.png)
> 
> Working on Ubuntu 22.04 (ami-09d56f8956ab235b3) deployed on a `t3.nano` instance in N. Virginia.

thank you!!!

**Comment by iramello** [comment] 2023-01-06 14:32
CodeDeploy: one of the worst products within AWS. If you need an update, they take years.
Minor mod on the script above to isolate version and easier the task on upgrades:

```bash
#!/bin/bash

# Installs CodeDeploy agent and its prerequisites on Ubuntu 22.04 given AWS CodeDeploy team doesn't exist

# https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-version-history
CODEDEPLOY_VERSION=1.4.1-2244

cd /tmp
wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/releases/codedeploy-agent_"$CODEDEPLOY_VERSION"_all.deb
mkdir codedeploy-agent_"$CODEDEPLOY_VERSION"_ubuntu22
dpkg-deb -R codedeploy-agent_"$CODEDEPLOY_VERSION"_all.deb codedeploy-agent_"$CODEDEPLOY_VERSION"_ubuntu22
sed 's/Depends:.*/Depends:ruby3.0/' -i ./codedeploy-agent_"$CODEDEPLOY_VERSION"_ubuntu22/DEBIAN/control
dpkg-deb -b codedeploy-agent_"$CODEDEPLOY_VERSION"_ubuntu22/
sudo dpkg -i codedeploy-agent_"$CODEDEPLOY_VERSION"_ubuntu22.deb

systemctl list-units --type=service | grep codedeploy
sudo systemctl status codedeploy-agent
```

**Comment by pixeltrix** [comment] 2023-01-23 15:46
Just an FYI on this thread that Ruby 2.7 is end-of-life in just over 2 months: https://endoflife.date/ruby

![image](https://user-images.githubusercontent.com/6321/214083472-ea521380-986e-4a4d-91b7-d0121a742855.png)

**Comment by alilland** [comment] 2023-01-24 18:50
ok, regardless of EOL for 2.7.x

what do I do right now if im using ubuntu 22 and ruby 2.7.7?

**Comment by wbelk** [comment] 2023-01-24 19:05
@alilland  Switch to debian, and write your own automation using systemd and bash. I had massive problems with both code deploy and ubuntu 22. Code deploy was grenading my ec2 server randomly while trying to spin up a new process. Removed code deploy and no more issues. The debian switch was for other (i think mostly unrelated) reasons, but snap and appArmor were causing so many stupid headaches, absolutely not worth it. Just my experience, your mileage may vary. I ended up with the strong feeling I would have saved much time and energy just doing my own from the start, but I thought oh cool, codeDeploy...nope.

**Comment by wbelk** [comment] 2023-01-24 19:06
> CodeDeploy: one of the worst products within AWS

Seems like *facts*

**Comment by alilland** [comment] 2023-01-24 19:13
I dont like this option, but what If I have rvm installed and I keep two rubies on the machine? 3.0.2 as the default for code deploy agent, and 2.7 for my application?

**Comment by SkullDesperados** [comment] 2023-02-01 16:34
Hello,
I allow myself to add solution for people who use RockyLinux or Centos 9.
I haven't found solution to force ruby 3 with CodeDeploy Agent, but I have found solution to have ruby 2.7 and openssl 1.1 on updated environnement with OpenSSL 3.

`
Install RVM packages managers for ruby
$> gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
$> dnf install curl gcc bzip2 openssl-devel libffi-devel readline-devel zlib-devel ncurses-devel which
$> curl -sSL https://get.rvm.io | bash -s stable
$> bash

Install OpenSSL 1.1 and Ruby 2.7 with RVM
$> rvm pkg install openssl
$> rvm install ruby-2.7 --with-openssl-dir=/usr/local/rvm/usr

Install AWS CodeDeploy Agent
$> dnf install chkconfig wget
$> mkdir /opt/aws-codedeploy 
$> cd /opt/aws-codedeploy
$> wget https://aws-codedeploy-eu-west-1.s3.eu-west-1.amazonaws.com/latest/install
$> chmod +x ./install
$> ./install auto
$> service codedeploy-agent status
`
I hope that will help you

**Comment by yacinehmito** [comment] 2023-02-05 20:11
CodeDeploy cannot be installed with Systems Manager on AL2022 for the same reason. It's a blocker.

**Comment by karlkatzke** [comment] 2023-02-20 17:14
Any status update on an official fix? June sure was a long time ago, and Ruby 2.7 is EOL in a month.

**Comment by rnhurt** [comment] 2023-02-20 21:26
We are in the process of upgrading our Rails apps to Ruby 3.0.5 and this is a huge blocker for us.  It's inconceivable that this agent doesn't support a more updated version of Ruby!  😡 

NOTE: I was actually able to remove the Ruby checks and it seems like the agent installed correctly.  However, I'm pretty sure that the auto-update function will try to update to the next version which will probably screw up somewhere/somehow.

**Comment by philstrong** [comment] 2023-02-21 23:42
The next version of the agent will support Ruby 3

**Comment by rnhurt** [comment] 2023-02-22 08:59
> The next version of the agent will support Ruby 3. We’re sorry for the delay in this support.

That's great news!  Any thoughts on when the next version might appear?  I don't even really need any new features or bug fixes, just adding Ruby 3.x support would be enough.  :grin:

**Comment by philstrong** [comment] 2023-02-22 23:03
Target is to begin shipping in early March and complete all commercial regions by mid March.

**Comment by alex-klepa** [comment] 2023-02-28 01:58
Amazon Linux 2022 script, with 3.1, 3.2 support

```bash
#!/bin/bash

# Installs CodeDeploy agent and its prerequisites on Ubuntu 22.04 given AWS CodeDeploy team doesn't exist
# https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-version-history
CODEDEPLOY_VERSION=1.4.1-2244


cd /tmp
wget https://aws-codedeploy-ap-southeast-2.s3.ap-southeast-2.amazonaws.com/releases/codedeploy-agent-"$CODEDEPLOY_VERSION".noarch.rpm
mkdir codedeploy-agent_"$CODEDEPLOY_VERSION"_al2022
rpm2cpio codedeploy-agent-"$CODEDEPLOY_VERSION".noarch.rpm |  (cd codedeploy-agent_"$CODEDEPLOY_VERSION"_al2022; cpio -idmv)
sudo cp -r codedeploy-agent_"$CODEDEPLOY_VERSION"_al2022/etc /
sudo cp -r codedeploy-agent_"$CODEDEPLOY_VERSION"_al2022/usr /

sudo git clone https://github.com/brandinfluencegroup/aws-codedeploy-agent.git /opt/codedeploy-agent

sudo dnf install chkconfig -y

sudo systemctl enable codedeploy-agent
sudo systemctl start codedeploy-agent
systemctl list-units --type=service | grep codedeploy
sudo systemctl status codedeploy-agent
```

**Comment by karlkatzke** [comment] 2023-02-28 04:10
I have it on good authority that codedeploy agent version 1.5 is in QA and will be released within a few weeks.

**Comment by alex-klepa** [comment] 2023-02-28 05:31
> I have it on good authority that codedeploy agent version 1.5 is in QA and will be released within a few weeks.

few weeks for ruby 3.0, few months for 3.1 and few years for 3.2 🤦

**Comment by t0shiii** [comment] 2023-03-01 22:06
> I have it on good authority that codedeploy agent version 1.5 is in QA and will be released within a few weeks.

Confirmed.  1.5 rollout is imminent and will add support for Ruby 3.x along with Ubuntu 22.04 LTS support.  Release notes and official docs coming soon.

**Comment by iramello** [comment] 2023-03-01 22:13
> > I have it on good authority that codedeploy agent version 1.5 is in QA and will be released within a few weeks.
> 
> Confirmed. 1.5 rollout is imminent and will add support for Ruby 3.0 along with Ubuntu 22.04 LTS support. Release notes and official docs coming soon.

Great to see it after only 27 months for ruby 3 and 11 months for Jammy! Thanks! <3

**Comment by t0shiii** [comment] 2023-03-08 22:57
FYI: as mentioned in #349 1.5.0 is live.  Installation instructions are linked in the announcement.

**Closed by t0shiii** 2023-03-08 22:57 UTC

**Comment by alex-klepa** [comment] 2023-03-08 23:05
as predicted, no 3.1 and 3.2 support

**Comment by alboyadjian** [comment] 2023-03-13 18:32
1.5 doesn't seem to be working under ruby3.1 for me. I'm getting the same issue as reported here
https://github.com/aws/aws-codedeploy-agent/issues/352

**Comment by rnhurt** [comment] 2023-03-13 19:57
> 1.5 doesn't seem to be working under ruby3.1 for me. I'm getting the same issue as reported here #352

I think v1.5 only supports Ruby 3.0.x, not Ruby v3.1.x (or v3.2.x).

**Comment by e200** [comment] 2023-04-06 22:58
Looks like they are forcing us to use Fargate.

**Comment by e200** [comment] 2023-04-06 22:59
AWS is forcing us to switch to Fargate.

**Comment by yacinehmito** [comment] 2023-04-07 01:58
> AWS is forcing us to switch to Fargate.

@e200 Just released Ruby 3.2 support. I don't think there's anything left to be complaining about.

**Comment by mwjones-aws** [comment] 2023-04-07 12:46
Correct, CodeDeploy Agent 1.6.0 adds support for Ruby 3.1 and 3.2. It has been deployed to most commercial AWS regions as of this comment.

Please track its rollout on #360

**Comment by e200** [comment] 2023-04-07 18:10
> > AWS is forcing us to switch to Fargate.
> 
> @e200 Just released Ruby 3.2 support. I don't think there's anything left to be complaining about.

My region is eu-south-2, that’s why.

**Comment by t0shiii** [comment] 2023-04-12 18:45
> 
> My region is eu-south-2, that’s why.

Hello, wanted to let you know that CodeDeploy Agent 1.6.0 is available in all commercial regions now including eu-south-2

**Comment by ring-pete** [comment] 2023-05-22 23:27
Will there be build artifacts available for v1.6.0?  this page still lists v1.5.0 as being the latest:

https://github.com/aws/aws-codedeploy-agent/releases

**Comment by t0shiii** [comment] 2023-05-22 23:30
@ring-pete I would recommend you install the latest CodeDeploy Agent using the installation instructions on the [official documentation](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-cli.html)

**Comment by ring-pete** [comment] 2023-05-22 23:32
I can't because AWS does not support FeeBSD.  Also, I would think you'd include the release in the same place as previous releases?

**Comment by t0shiii** [comment] 2023-05-22 23:47
@ring-pete Just published it.  Here is a link to the release: https://github.com/aws/aws-codedeploy-agent/releases/tag/1.6.0
