### ISSUE TITLE
Installation broken on Ubuntu 20.04

### ISSUE THREAD

**Issue by autarchprinceps** [aws/aws-codedeploy-agent#239] opened 2020-04-06 19:36 UTC
Following the official guide to installing fails on Ubuntu 20.04 with the following error:
Traceback (most recent call last):
	8: from /tmp/codedeploy-agent-install:33:in `<main>'
	7: from /tmp/codedeploy-agent-install:33:in `new'
	6: from /usr/lib/ruby/2.7.0/logger.rb:389:in `initialize'
	5: from /usr/lib/ruby/2.7.0/logger.rb:389:in `new'
	4: from /usr/lib/ruby/2.7.0/logger/log_device.rb:18:in `initialize'
	3: from /usr/lib/ruby/2.7.0/logger/log_device.rb:83:in `set_dev'
	2: from /tmp/codedeploy-agent-install:21:in `method_missing'
	1: from /tmp/codedeploy-agent-install:21:in `map'
/tmp/codedeploy-agent-install:22:in `block in method_missing': undefined method `path' for #<IO:<STDOUT>> (NoMethodError)

**Comment by C2L2C** [comment] 2020-04-27 17:44
Yup, same issue.

**Comment by Helen1987** [comment] 2020-04-28 00:04
CodeDeploy Agent does not support Ubuntu 20.x so far. Check our [documentation](https://docs.aws.amazon.com/en_us/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-supported-operating-systems). The support is in our plan

**Comment by C2L2C** [comment] 2020-04-28 08:15
Is there a timeline when the supported version will be released?

**Comment by cmllamosas** [comment] 2020-04-29 16:57
@Helen1987 there are some other related (or duplicated) issues [#242](https://github.com/aws/aws-codedeploy-agent/issues/242), [#243](https://github.com/aws/aws-codedeploy-agent/issues/243), it will be great to give us support on this support request.

**Comment by lifeeth** [comment] 2020-05-01 09:01
A possible workaround:

* A compatible ruby version could be installed using snap - `snap install ruby --channel=2.5/stable --classic` and then proceed to install using the manual instructions in the README
* This might mess up things if you are using any other package / code that rely on system ruby
* Gist with all the steps needed to run codedeploy agent as a systemd service https://gist.github.com/lifeeth/557722cd62eb41010807ad1a2ce6ba41

**Comment by osterik** [comment] 2020-05-02 00:29
worked for me: repack .deb package and add ruby 2.7 as compatible instead of outdated 2.0:
```
apt-get update
apt-get install -y ruby
wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/releases/codedeploy-agent_1.0-1.1597_all.deb
mkdir a2 codedeploy-agent_1.0-1.1597_ubuntu20
dpkg-deb -R codedeploy-agent_1.0-1.1597_all.deb codedeploy-agent_1.0-1.1597_ubuntu20
sed 's/2.0/2.7/' -i ./codedeploy-agent_1.0-1.1597_ubuntu20/DEBIAN/control
dpkg-deb -b codedeploy-agent_1.0-1.1597_ubuntu20
dpkg -i codedeploy-agent_1.0-1.1597_ubuntu20.deb
systemctl start codedeploy-agent
systemctl enable codedeploy-agent
```
tnx to @takenoko-str for this [AWS CodeDeploy Agent install script (Ubuntu 18 LTS)](https://gist.github.com/takenoko-str/810c80f82d495eadcd980fc79d6fae7e)

**Comment by cmllamosas** [comment] 2020-05-04 02:42
@osterik that snippet works fine, thank you.

**Comment by sapphirecat** [comment] 2020-05-18 14:10
Is there a time frame where this is expected to be resolved, or should I consider CodeDeploy to be deprecated/abandoned?

**Comment by Helen1987** [comment] 2020-05-19 01:50
@sapphirecat, CodeDeploy is not deprecated. We are actively working on changing our release process for the Agent. The fix will be released as soon as we switch to a new release process

**Comment by fleaz** [comment] 2020-05-24 17:48
Not to sound rude but the last release is from late 2018, there where just a hand full of commits since then, the most recent Ubuntu version you support is 16.04, and angry people are pilling up in the GitHub issues because from an outside perspective this project is totally dead...

Not even your own PAID support could give me some informations on this and just gave the hint to just restart the agent every time to "resolve" the memory leak which is present since nearly 4 or 5 years now. And the only information we get from you since February is "we are working on a new release process". As a customer this is totally frustrating that a multi billion dollar company with some of the best software devs in the world is not able to maintain a little Ruby tool on which thousands of paying customers depend on in their day-to-day business.

can you give us at least a rough estimates on when the "new release process" will be finished? 16.04 will be EOL in 2024, so please don't take THAT long...

**Comment by brblck** [comment] 2020-05-28 17:48
Hi Folks. 👋 

I'm the new SDM for the CodeDeploy teams at AWS and I wanted to chime in here briefly. 

While we don't have any public dates we can share at the moment, we are concurrently working on several successive and very near-term releases to the CodeDeploy agent. These releases will include a litany fixes and features that many members of the community have been asking for including a resolution to this issue of Ubuntu support. 

Part of the delay at the moment is that we're putting in place a better set of release and update mechanisms (as Alena mentioned). This upfront investment will pave the way for both faster and safer iterations with the agent -- allowing us to release our work as well as community contributions much quicker and more frequently.

We're also working on a plan to share a public version of the CodeDeploy roadmap with you so that our customer community can have better insight into our vision for the CodeDeploy agent and the timelines around it.

We appreciate your patience while we get all this work completed, but rest assured a lot is happening even though it isn't all visible to you yet.

**Comment by ydesgagn** [comment] 2020-06-16 15:20
Hi,

Here is my way of doing it patching an unfixed bug when deleting files even on master at the same time.

```
# install aws codedeploy (manually to apply a patch when deleting files)
git clone https://github.com/aws/aws-codedeploy-agent.git
mv aws-codedeploy-agent /opt/codedeploy-agent
cd /opt/codedeploy-agent
git checkout tags/v1.0-1.1597
sed -i.bak -e 's/FileUtils\.rmdir.@file_path./FileUtils.rmdir\(\@file_path\) rescue StandardError/g' /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/install_instruction.rb
bundle install --system
chown -R root:root /opt/codedeploy-agent
chmod 644 /opt/codedeploy-agent/conf/codedeployagent.yml
chmod 755 /opt/codedeploy-agent/init.d/codedeploy-agent
chmod 644 /opt/codedeploy-agent/init.d/codedeploy-agent.service
mkdir -p /etc/codedeploy-agent
ln -s /opt/codedeploy-agent/conf /etc/codedeploy-agent/conf
mv /opt/codedeploy-agent/init.d/codedeploy-agent /etc/init.d/codedeploy-agent
grep -v "After=" /opt/codedeploy-agent/init.d/codedeploy-agent.service >/lib/systemd/system/codedeploy-agent.service
sed -i.bak '2,8d' /etc/init.d/codedeploy-agent
rm -f /etc/init.d/codedeploy-agent.bak
/etc/init.d/codedeploy-agent start
/usr/sbin/update-rc.d codedeploy-agent defaults
/usr/sbin/update-rc.d codedeploy-agent enable
rm -rf .git CODE_OF_CONDUCT.md CONTRIBUTING.md Gemfile.lock LICENSE NOTICE README.md Rakefile buildspec-agent-rake.yml coverage deployment features spec test
```

**Comment by AnandarajuCS** [comment] 2020-08-05 00:24
This issue is fixed in our latest release v1.1.2 
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-codedeploy-agent-improved-compatibility-amazon-linux-windows-ubuntu/

**Closed by AnandarajuCS** 2020-08-05 00:24 UTC
Labels: enhancement, feature-request

**Comment by satishvis** [comment] 2020-08-20 17:52
The issue still persists in Ubuntu 20.04...

**Comment by fossterer** [comment] 2020-09-02 12:06
@AnandarajuCS @brblck I just encountered this while setting up the `install` script.

**Instance:** Ubuntu 20.04
**Download info:** wget https://aws-codedeploy-ca-central-1.s3.ca-central-1.amazonaws.com/latest/install
**Result:**

````
$ sudo ./install auto
Traceback (most recent call last):
        8: from ./install:34:in `<main>'
        7: from ./install:34:in `new'
        6: from /usr/lib/ruby/2.7.0/logger.rb:389:in `initialize'
        5: from /usr/lib/ruby/2.7.0/logger.rb:389:in `new'
        4: from /usr/lib/ruby/2.7.0/logger/log_device.rb:18:in `initialize'
        3: from /usr/lib/ruby/2.7.0/logger/log_device.rb:83:in `set_dev'
        2: from ./install:22:in `method_missing'
        1: from ./install:22:in `map'
./install:23:in `block in method_missing': undefined method `path' for #<IO:<STDOUT>> (NoMethodError)
````

Going with the fix by @osterik for now

**Comment by developerayyo** [comment] 2020-09-12 01:51
> @AnandarajuCS @brblck I just encountered this while setting up the `install` script.
> 
> **Instance:** Ubuntu 20.04
> 
> **Ruby info:**
> 
> ```
> $ ruby --version
> ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
> ```
> 
> **Download info:** wget https://aws-codedeploy-ca-central-1.s3.ca-central-1.amazonaws.com/latest/install
> 
> **Result:**
> 
> ```
> $ sudo ./install auto
> Traceback (most recent call last):
>         8: from ./install:34:in `<main>'
>         7: from ./install:34:in `new'
>         6: from /usr/lib/ruby/2.7.0/logger.rb:389:in `initialize'
>         5: from /usr/lib/ruby/2.7.0/logger.rb:389:in `new'
>         4: from /usr/lib/ruby/2.7.0/logger/log_device.rb:18:in `initialize'
>         3: from /usr/lib/ruby/2.7.0/logger/log_device.rb:83:in `set_dev'
>         2: from ./install:22:in `method_missing'
>         1: from ./install:22:in `map'
> ./install:23:in `block in method_missing': undefined method `path' for #<IO:<STDOUT>> (NoMethodError)
> ```
> 
> Going with the fix by @osterik for now

Same here.. just experienced this too.

**Comment by ahmedyounis** [comment] 2020-09-19 18:39
@osterik you are the man

**Comment by peillis** [comment] 2020-09-21 11:42
Same here. Why is this issue closed?

**Comment by micmich** [comment] 2020-09-24 14:43
Issue still exists.
Downloaded http://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install on 2020.09.24T16.43 and got failure as described.

**Comment by fleaz** [comment] 2020-09-25 14:01
Okay, know you got me curious because after migrating a lot of customers to Ubuntu Focal I was really confused by the amount of people who still have bugs with this so I started digging :D

We setup all our servers with a standardized AMI which we build with Packer and Chef. One of the cookbooks is responsible for installing the latest CodeDeploy agent and this cookbook just runs fine with the latest version and we have the latest Codedeploy Agent installed afterwards.

Now the funny part: When I start the exact same base AMI by hand and try to execute the installer I get the error from the first post... :confused: 
Thinking about this for a while what the differences could be, I read the error message again and stumbled upon the `io:STDOUT` part of the errormessage. And yes, thats the only difference: Chef runs its cookbooks non-interactively, so there is no real stdout present. Therefore the easiest way to fix the installer is to redirect its output into a file, and yes this fixed the problem :tada: 

![Screenshot_2020-09-25_16:00:25](https://user-images.githubusercontent.com/2489598/94276234-3f1fd380-ff48-11ea-95dc-c95a3dd39229.png)

tl,dr: Yes this bug should still be open, but can be circumvented with an easy workaround :)

**Comment by erikcc02** [comment] 2020-09-29 01:41
@fleaz this worked for me. Thank you!

**Comment by kksmartexchange** [comment] 2020-10-04 12:48
thanks @fleaz 

`$ sudo ./install auto > /tmp/logfile` - worked for me

**Comment by philstrong** [comment] 2021-01-26 15:49
duplicate of https://github.com/aws/aws-codedeploy-agent/issues/264

**Comment by alilland** [comment] 2021-07-21 23:21
```bash
$ sudo ./install auto > /tmp/logfile
/usr/bin/env: ‘ruby’: No such file or directory
```
no longer works for Ubuntu 20.04, I have experienced this working in the past but ran into issues today...
