### ISSUE TITLE
codedeploy don't support overwrite file in codepipeline

### ISSUE THREAD

**Issue by zjjott** [aws/aws-codedeploy-agent#145] opened 2017-12-14 04:33 UTC
I have read #14 ,but until now ,there is not support in codepipeline to overwrite file

**Comment by rohkat-aws** [comment] 2018-06-04 17:35
@zjjott not sure if this is supposed to be a codedeploy issue?

**Comment by huribeir** [comment] 2018-06-04 23:44
@rohkat-aws I think he meant CodeDeploy...this is around the fact that we currently can't specify Content Options using the appspec file.

**Comment by rohkat-aws** [comment] 2018-06-04 23:48
@huribeir seems like a feature request to me, if you can just explain it a little bit more. We can look into it ,if its feasible.

**Comment by huribeir** [comment] 2018-06-04 23:52
Yes definitely a feature request, and documented on #14. Information is that this has been already added as a feature request back in 2015.

**Comment by quentinhayot** [comment] 2018-06-19 08:22
This feature needs some love guys, come on... It's been 3 years !
When using CodePipeline, you can't really use the CLI to allow files overwriting, can you ?

**Comment by pandeyprateek** [comment] 2018-06-26 06:34
any update on this feature?

**Comment by RobinCowash** [comment] 2019-07-12 10:27
Need it so much!

**Comment by quentinhayot** [comment] 2019-07-12 10:51
Yeah, any news on this ?

**Comment by BartusZak** [comment] 2019-12-11 06:49
So I do need to remove it every time when I finish deployment...

**Comment by josjaf** [comment] 2020-02-16 20:50
+1 for this feature!

**Comment by gantta** [comment] 2020-02-22 16:46
+1 for this feature

**Comment by hanischandrew** [comment] 2020-03-11 15:09
+1 for this feature

**Comment by teamhide** [comment] 2020-05-14 03:41
Any new feature here?

**Comment by iddriss** [comment] 2020-05-25 21:16
Any update here?

**Comment by Helen1987** [comment] 2020-05-26 04:45
Can be fixed after #14 is fixed

**Comment by Helen1987** [comment] 2020-05-26 04:49
Should be fixed alongside with #14

**Comment by brblck** [comment] 2020-09-15 15:33
Duplicate of #14

**Closed by brblck** 2020-09-15 15:33 UTC
Labels: feature-request
