### ISSUE TITLE
CodeDeploy Agent never exits even when it's children consistently fail.

### ISSUE THREAD

**Issue by glennpratt** [aws/aws-codedeploy-agent#123] opened 2017-07-07 21:22 UTC
On many servers over the past few days, we've seen CodeDeploy agent children start failing. It seems something about Ruby has broken in the processes environment. If codedeploy-agent would exit, a service manager can restart it or alert on the issue. Instead, it just continues to fail until a human restarts it.

(Note: this is running on baked AMIs, Ruby or gems do not change underneath the process).

```
2017-07-07 00:00:03 ERROR [codedeploy-agent(23923)]: booting child: error during start or run: SystemExit...skipping...
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/json.rb:64:in `<module:Json>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/json.rb:5:in `<module:Aws>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/json.rb:3:in `<top (required)>'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/protocols/json_rpc.rb:23:in
 `<class:JsonRpc>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/protocols/json_rpc.rb:15:in
 `<module:Protocols>'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_
with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in s
pawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_chil
d'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 l
evels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create
_with_logging_context'
2017-07-07 21:13:58 INFO  [codedeploy-agent(13436)]: master 13436: Received CHLD - cleaning dead child pr
ocess
2017-07-07 21:13:58 INFO  [codedeploy-agent(13436)]: master 13436: been told to replace child 28287
2017-07-07 21:13:58 INFO  [codedeploy-agent(13436)]: master 13436: not enough child processes running - m
issing at least 1 - respawning
2017-07-07 21:14:03 INFO  [codedeploy-agent(13436)]: master 13436: Spawned child 1/1
2017-07-07 21:14:03 INFO  [codedeploy-agent(28355)]: On Premises config file does not exist or not readab
le
2017-07-07 21:14:03 ERROR [codedeploy-agent(28355)]: booting child: error during start or run: NoMethodEr
ror - undefined method `missing_extensions?' for nil:NilClass - /opt/rh/rh-ruby23/root/usr/share/rubygems
/rubygems/stub_specification.rb:148:in `missing_extensions?'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/basic_specification.rb:71:in `contains_requirable_file
?'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/specification.rb:1037:in `block in find_by_path'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/specification.rb:1036:in `each'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/specification.rb:1036:in `find'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/specification.rb:1036:in `find_by_path'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems.rb:189:in `try_activate'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:40:in `require'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/json.rb:42:in `oj_engine'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/json.rb:64:in `<module:Json>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/json.rb:5:in `<module:Aws>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/json.rb:3:in `<top (required)>'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/protocols/json_rpc.rb:23:in
 `<class:JsonRpc>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/protocols/json_rpc.rb:15:in
 `<module:Protocols>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/protocols/json_rpc.rb:15:in
 `<module:Protocols>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/protocols/json_rpc.rb:3:in `<module:Plugins>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/protocols/json_rpc.rb:2:in `<module:Aws>'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/protocols/json_rpc.rb:1:in `<top (required)>'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:136:in `const_get'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:136:in `block in require_plugin'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:135:in `each'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:135:in `require_plugin'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:105:in `plugin'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:59:in `block in each'
/opt/rh/rh-ruby23/root/usr/share/ruby/set.rb:306:in `each_key'
/opt/rh/rh-ruby23/root/usr/share/ruby/set.rb:306:in `each'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:73:in `block in each_plugin'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:72:in `synchronize'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:72:in `each_plugin'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugin_list.rb:58:in `each'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/base.rb:170:in `to_a'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/base.rb:170:in `Array'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/base.rb:170:in `plugins'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/base.rb:213:in `build_plugins'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-2.9.9/lib/seahorse/client/base.rb:101:in `new'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/codedeploy_control.rb:41:in `get_client'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:28:in `initialize'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `new'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `runner'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `block in prepare_run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:30:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2017-07-07 21:14:03 ERROR [codedeploy-agent(28355)]: booting child: error during start or run: SystemExit - exit - /opt/codedeploy-agent/lib/instance_agent/runner/child.rb:67:in `exit'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:67:in `rescue in with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:30:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2017-07-07 21:14:03 INFO  [codedeploy-agent(13436)]: master 13436: Received CHLD - cleaning dead child process
2017-07-07 21:14:03 INFO  [codedeploy-agent(13436)]: master 13436: been told to replace child 28355
2017-07-07 21:14:03 INFO  [codedeploy-agent(13436)]: master 13436: not enough child processes running - missing at least 1 - respawning
```

**Comment by asaf-erlich** [comment] 2017-07-10 17:43
Do you know which version of the agent you're running? Can you check the .version file inside /opt/codedeploy-agent/ ?

**Comment by glennpratt** [comment] 2017-07-10 17:59
```
[gpratt@XXXXXXXXXXXX ~]$ cat /opt/codedeploy-agent/.version
agent_version: OFFICIAL_1.0-1.1095_rpm
```

It seems like it would be helpful to log the contents instead of this:

```
2017-07-07 21:17:10 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:50 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:50 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:51 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:52 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:52 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:52 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:52 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:53 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:54 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:54 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:54 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:55 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:55 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:55 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:56 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:57 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:57 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:17:57 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:02 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:03 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:03 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:03 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:03 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:04 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:05 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:05 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:05 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:18:06 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:19:07 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:20:09 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:21:11 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:22:13 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:23:14 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:24:15 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:25:17 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:26:19 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:27:20 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:28:22 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:29:23 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:30:25 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:31:27 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:32:28 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
2017-07-07 21:33:30 INFO  [codedeploy-agent(28897)]: Version file found in /opt/codedeploy-agent/.version.
```

**Comment by asaf-erlich** [comment] 2017-07-11 23:17
1. I agree that the logging of version file found is wasteful and will try to fix that in future versions of the agent.

2. Which region is your host in? I want to verify that the agent is the newest version in that region. You're using a slightly out-of-date agent, although I don't think we've fixed this issue since then it wouldn't hurt to update too and then verify we still see the issue.

3. I realize this is asking for a lot since this is one of those Heisenbugs (see https://en.wikipedia.org/wiki/Heisenbug ) that are hard to replicate, but do you know of a way to easily reproduce this error so I can fix it? I wonder if I manually sudo kill the child process if it does a good job of replicating it.

**Comment by glennpratt** [comment] 2017-07-12 04:27
1. Thanks.
2. us-east-1. We are using the latest tag on GitHub. I believe we still allow CodeDeploy Agent to self update, but we are probably removing that.
3. I'd imagine removing or putting an error in a Ruby file the child will load would do it, but I haven't tried. I can try tomorrow.

**Comment by roy211** [comment] 2018-02-02 16:26
Hello
Same problem. But it is working now having applied the following changes:

`gem uninstall aws-sdk-3.0.1`
`gem uninstall aws-sdk-core`

restart codedeployagent.

note: update gem with `sudo gem update --system` if required??

this AWS EMR clusters

**Comment by rohkat-aws** [comment] 2018-04-24 20:43
@roy211 the agent comes shipped with aws-sdk ver 2 and hence when you install the sdk , it lacks some of the require's hence the unistall of sdk v3 was needed.

**Comment by annamataws** [comment] 2018-08-02 18:30
Issue #60 is about upgrading AWS SDK, which will fix this.
Closing issue. Track the progress in #60

**Closed by annamataws** 2018-08-02 18:30 UTC
Labels: bug
